version: 2.1
orbs:
  android: circleci/android@2.0.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum  "application/build.gradle" }}-{{ checksum  "core_network/build.gradle" }}-{{ checksum  "feature-movies/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum  "application/build.gradle" }}-{{ checksum  "core_network/build.gradle" }}-{{ checksum  "feature-movies/build.gradle" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlintFormat
      - run:
          name: Run lint
          command: ./gradlew lint
  danger:
    working_directory: ~/code
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Run danger
          command: bundle exec danger
workflows:
  build:
    jobs:
      - build
      - danger
