version: 2.1
orbs:
  android: circleci/android@2.0.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum  "application/build.gradle" }}-{{ checksum  "core_network/build.gradle" }}-{{ checksum  "feature-movies/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum  "application/build.gradle" }}-{{ checksum  "core_network/build.gradle" }}-{{ checksum  "feature-movies/build.gradle" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlintFormat
      - run:
          name: Run lint
          command: ./gradlew lint
      - run:
          name: Run danger
          command: bundle exec danger --verbose
workflows:
  build:
    jobs:
      - build 508ee4a49f1af7efa37d095f13736c72a04504cb