version: 2.1
orbs:
  android: circleci/android@2.0.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum  "application/build.gradle" }}-{{ checksum  "core_network/build.gradle" }}-{{ checksum  "feature-movies/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum  "application/build.gradle" }}-{{ checksum  "core_network/build.gradle" }}-{{ checksum  "feature-movies/build.gradle" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlintFormat
      - run:
          name: Run lint
          command: ./gradlew lint
      - run:
          name: Run danger
          command: bundle exec danger --verbose
  check:
    working_directory: ~/code
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: saddler-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - run:
          name: Run danger
          command: bundle exec danger
      - run:
          name: Move artifacts
          command: |
            ARTIFACTS="/tmp/circle_artifacts"
            mkdir -p "$ARTIFACTS"
            cp -v "app/build/reports/checkstyle/checkstyle.xml" "$ARTIFACTS/"
            cp -v "app/build/reports/findbugs/findbugs.xml" "$ARTIFACTS/"
            cp -v "app/build/reports/pmd/pmd.xml" "$ARTIFACTS/"
            cp -v "app/build/reports/pmd/cpd.xml" "$ARTIFACTS/"
            cp -v "app/build/reports/lint-results.xml" "$ARTIFACTS/"
      - save_cache:
          paths:
            - vendor/bundle
          key: saddler-gems-{{ checksum "Gemfile.lock" }}
      - store_artifacts:
          path: "/tmp/circle_artifacts"
workflows:
  build:
    jobs:
      - build
      - check:
          requires:
            - build
